--CURSORES
SET SERVEROUTPUT ON
DECLARE
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN
    OPEN C1;
    LOOP 
        FETCH C1 INTO V1;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    END LOOP;
   
    CLOSE C1;
END;
/

DECLARE
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN
    FOR i IN C1 LOOP 
    DBMS_OUTPUT.PUT_LINE(i.REGION_NAME);
    END LOOP;
END;
/
--SIN DECLARAR EL CURSOR
   
BEGIN
    FOR i IN (SELECT*FROM REGIONS) LOOP 
    DBMS_OUTPUT.PUT_LINE(i.REGION_NAME);
    END LOOP;
END;
/
--CON UN PARÁMETRO
DECLARE
    CURSOR C1(SALARIO NUMBER) IS SELECT * FROM EMPLOYEES WHERE SALARY > SALARIO;
    EMP1 EMPLOYEES%ROWTYPE;
BEGIN
     FOR i IN C1(10000) LOOP 
    DBMS_OUTPUT.PUT_LINE(i.FIRST_NAME || '-' || i.SALARY);
    END LOOP;
END;
/
DECLARE
    CURSOR CUR IS SELECT * FROM EMPLOYEES FOR UPDATE;
    EMP1 EMPLOYEES%ROWTYPE;
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO EMPL;
        EXIT WHEN CUR%NOTFOUND;
        IF EMPL.COMMISION_PCT IS NOT NULL THEN 
        UPDATE EMPLOYEES SET SALARY=SALARY*1.10 WHERE CURRENT OF CUR;
        ELSE 
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO');
        END IF;
    END LOOP;
    CLOSE CUR;
END;
