--EXCEPCIONES O ERRORES
SET SERVEROUTPUT ON
DECLARE 
MI_EXCEP EXCEPTION;
PRAGMA EXCEPTION_INIT(MI_EXCEP, -937);

v1 NUMBER;
v2 NUMBER;
begin
SELECT EMPLOYEE_ID,SUM(SALARY) INTO v1,v2 FROM EMPLOYEES;

EXCEPTION 
WHEN MI_EXCEP THEN
DBMS_OUTPUT.PUT_LINE('FUNCION INCORRECTA');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO');
END;
/
SET SERVEROUTPUT ON
DECLARE 
empl employees%rowtype;
begin
select * into empl from employees where employee_id>1;
DBMS_OUTPUT.PUT_LINE(EMPL.FIRST_NAME);
EXCEPTION
WHEN no_data_found THEN
    DBMS_OUTPUT.PUT_LINE(EMPL.FIRST_NAME);
WHEN too_many_rows THEN
    DBMS_OUTPUT.PUT_LINE('mas de una fila');
end;
/