--FUNCIONES PARA-- MOSTRAR DATOS SELECT ETC
CREATE OR REPLACE FUNCTION CALC_TAX_FN(EMPL IN EMPLOYEES.EMPLOYEE_ID%TYPE, T1 NUMBER) RETURN NUMBER
IS
    TAX NUMBER:=0;
    SAL EMPLOYEES.SALARY%TYPE:=0;
BEGIN
     SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID=EMPL;
    TAX:=SAL*T1/100;
    RETURN TAX;
END;
/
SET SERVEROUTPUT ON
DECLARE 
A NUMBER:=120;
B NUMBER:=5;
R NUMBER;
BEGIN
   
    R:=CALC_TAX_FN(A,B);
    DBMS_OUTPUT.PUT_LINE('R: ' || R);
END;
/
